version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Bangkok"
    reviewers:
      - "rtsp"
    assignees:
      - "rtsp"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Bangkok"
    reviewers:
      - "rtsp"
    assignees:
      - "rtsp"
